stages:
  prepare:
    cmd: '" -p" prepare.names,prepare.nc,prepare.train,prepare.test,prepare.test_size,prepare.random_state
      " -d" src/features/prepare.py " -d" data/raw/train.txt " -d" data/raw/test.txt
      " -o" data/processed/train/train.txt " -o" data/processed/test/test.txt " python"
      -m prepare'
