stages:
  prepare:
    cmd: python -m scripts.prepare
    deps:
    - data/raw/test.txt
    - data/raw/train.txt
    - scripts/prepare.py
    params:
    - prepare.names
    - prepare.nc
    - prepare.random_state
    - prepare.test
    - prepare.test_size
    - prepare.train
    outs:
    - data/processed/test_images.txt
    - data/processed/train_images.txt
